# Generated by Django 3.2.20 on 2023-07-26 19:06

import cart.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=22, unique=True, validators=[cart.validators.check_bank_account])),
                ('bic', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
            ],
        ),
    ]
