# Generated by Django 3.2.20 on 2023-07-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_bankaccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankAccount',
            new_name='БанковиСметки',
        ),
    ]
