#version: '3.4'
#services:
#  postgres:
#    image: postgres
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_PASSWORD: "VA0885281774"
#      POSTGRES_USER: "postgres"
#      POSTGRES_DB: "estore"
#      PGDATA: /var/lib/postgresql/data/pgdata
#    volumes:
#      - ./postgresql:/var/lib/postgresql/data
#  estore:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres

version: '3.4'

services:
  estore:
    image: estore
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ecom/.env
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: VA0885281774
      POSTGRES_USER: postgres
      POSTGRES_DB: estore
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data