version: '3.4'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "estore"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    user: "${UID}:${GID}"
    environment:
      PGADMIN_DEFAULT_EMAIL: "profin.e.store@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    ports:
      - "5433:80"
    depends_on:
      - postgres