version: '3.4'

services:
  estore:
    build: .
    command: gunicorn ecom.wsgi:application
    platform: linux/amd64
    ports:
      - "8000:8000"
    env_file:
      - ecom/.env
    volumes:
      - /tmp/Django_eCommerce/static:/app/static
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    user: "postgres"
    environment:
      POSTGRES_PASSWORD: VA0885281774
      POSTGRES_USER: postgres
      POSTGRES_DB: estore
      PGDATA: /var/lib/postgresqlite/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresqlite/data

  nginx:
    image: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - /tmp/Django_eCommerce/static:/home/app/web/static
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - estore