# Generated by Django 3.2.20 on 2023-07-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='stripe_customer_id',
        ),
    ]
