# Generated by Django 3.2.20 on 2023-07-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_bankaccount_банковисметки'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='БанковиСметки',
            new_name='Банкови_Сметки',
        ),
    ]
