# Generated by Django 3.2.20 on 2023-07-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20230727_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bic',
            new_name='BIC',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='iban',
            new_name='IBAN',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
